name: "Deploy ChitChat"

on:
  push:
    tags:
      - "**"

env:
  PROJECT_PATH: ChitChat.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - run: dotnet restore ${{ env.PROJECT_PATH }} -r win-x64

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore -p:PublishSingleFile=true --self-contained -r win-x64

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: bin/Release/net8.0-windows/publish/win-x64/*.exe
          release-url: ${{ steps.release_action.outputs.upload_url }}