name: "Deploy ChitChat"

on:
  push:
    tags:
      - "**"

env:
  PROJECT_PATH: ChitChatClient/ChitChatClient.csproj
  LAUNCHER_PATH: ChitChatLauncher/ChitChatLauncher.csproj

jobs:
  create-release:
    runs-on: windows-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get changelog
        id: get_changelog
        run: echo "release_notes=$(cat release_notes.md)" >> $GITHUB_OUTPUT

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.get_changelog.outputs.release_notes }}

  deploy-client:
    runs-on: windows-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - run: dotnet restore ${{ env.PROJECT_PATH }} -r win-x64

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore -p:PublishSingleFile=true --self-contained -r win-x64

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build
  
      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "D:/a/ChitChat/ChitChat/ChitChatClient/bin/Release/net8.0-windows/win-x64/publish/*.exe"
          release-url: ${{ needs.create-release.outputs.upload_url }}


  deploy-launcher:
    runs-on: windows-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
  
      - run: dotnet restore ${{ env.LAUNCHER_PATH }} -r win-x64

      - run: dotnet build ${{ env.LAUNCHER_PATH }} -c Release --no-restore -p:PublishSingleFile=true --self-contained -r win-x64

      - run: dotnet publish ${{ env.LAUNCHER_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build
  
      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: "D:/a/ChitChat/ChitChat/ChitChatLauncher/bin/Release/net8.0-windows/win-x64/publish/*.exe"
          release-url: ${{ needs.create-release.outputs.upload_url }}